name: Docker

on:
  schedule:
    - cron: '59 12 1 * *'
  push:
    branches: [ master ]
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '**.md'
  workflow_dispatch:
    inputs:
      args:
        description: 'build arguments (GCC ARDUINO)'
        required: false
        default: ''

env:
  REGISTRY: docker.io
  IMAGE_NAME: nuno351/gentooino
  # not using build.strategy so layers are re-used
  GCC_VERSIONS: ~9.5.0 ~10.4.0

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build image
      run: |
        export MAKEOPTS="-j$(nproc)"
        echo "Removing tmpfs from gcc compilation layer"
        sed -i -e 's|--mount.*portage/||' Dockerfile
        if [[ -z "${{ github.event.inputs.args }}" ]]; then
          for gcc in $GCC_VERSIONS; do
            echo "Building image for gcc $gcc..."
            bash build.sh $gcc
          done
        else
          echo Manual build ${{ github.event.inputs.args }}
          bash build.sh ${{ github.event.inputs.args }}
        fi

    - name: Inspect image
      run: |
        docker images
        docker image inspect "${IMAGE_NAME}"

    - name: Login to Docker Registry
      uses: docker/login-action@v2
      if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/master'
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push image
      if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/master'
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
      run: docker push --all-tags "${IMAGE_NAME}"
